# ==========================================
# 基本配置
# ==========================================
bind [::]:6053
bind-tcp [::]:6053
cache-size 8192
rr-ttl-min 300
serve-expired yes
serve-expired-ttl 259200
prefetch-domain yes
speed-check-mode ping,tcp:80,tcp:443
force-AAAA-SOA yes
force-qtype-SOA 28
dualstack-ip-selection no
hosts-file /etc/hosts
dnsmasq-lease-file /tmp/dnsmasq.leases
log-level error
log-file /tmp/smartdns.log
log-size 200K
log-console	yes

# ==========================================
# 1. 默认组
# ==========================================
# 内网 DNS
server 192.168.123.6 -g china
# 阿里 DoH
server-https https://dns.alidns.com/dns-query
# 腾讯 DoH
server-https https://doh.pub/dns-query
# 360 DoH
server-https https://doh.360.cn/dns-query

# ==========================================
# 2. Bootstrap 引导解析组
# ==========================================
server 223.5.5.5 -b -e
server 119.29.29.29 -b -e

# ==========================================
# 3. 国内通用组
# ==========================================
server 223.5.5.5 -g china -g ali -e
server 223.6.6.6 -g china -g ali -e
server 119.29.29.29 -g china -g tencent -e
server 119.28.28.28 -g china -g tencent -e
server 180.184.1.1 -g china -g bytedance -e
server 180.184.2.2 -g china -g bytedance -e

# ==========================================
# 域名分流规则加载区
# ==========================================
# dnsmasq-china-list
domain-set -name china_list -file /etc_ro/smartdns/accelerated-domains.china.raw.txt
domain-rules /domain-set:china_list/ -nameserver china -speed-check-mode tcp:80
# 阿里
domain-set -name ali_domains -file /etc_ro/smartdns/domains-ali.txt
domain-rules /domain-set:ali_domains/ -nameserver ali -speed-check-mode none
# 腾讯
domain-set -name tencent_domains -file /etc_ro/smartdns/domains-tencent.txt
domain-rules /domain-set:tencent_domains/ -nameserver tencent -speed-check-mode none
# 字节
domain-set -name bytedance_domains -file /etc_ro/smartdns/domains-bytedance.txt
domain-rules /domain-set:bytedance_domains/ -nameserver bytedance -speed-check-mode none

