# ==========================================
# 基本配置
# ==========================================
bind [::]:6053
bind-tcp [::]:6053
server-name smartdns
cache-size 8192
cache-persist no
rr-ttl 600
rr-ttl-min 300
max-reply-ip-num 2
log-level error
log-file /tmp/smartdns.log
log-size 200K
log-num 2
speed-check-mode none
hosts-file /etc/hosts
force-AAAA-SOA yes
dnsmasq-lease-file /tmp/dnsmasq.leases
serve-expired yes
serve-expired-ttl 86400
dualstack-ip-selection no

# ==========================================
# 1. 默认组
# ==========================================
# Cloudflare DoH
server-https https://dns.cloudflare.com/dns-query
# OpenDNS DoH
server-https https://dns.sse.cisco.com/dns-query
# 阿里 DoH
#server-https https://dns.alidns.com/dns-query
# 腾讯 DoH
#server-https https://doh.pub/dns-query
# 360 DoH
#server-https https://doh.360.cn/dns-query

# ==========================================
# 2. Bootstrap 引导解析组
# ==========================================
server 180.76.76.76 -b -e
server 101.226.4.6 -b -e

# ==========================================
# 3. 国内组
# ==========================================
server 223.5.5.5 -g china -g ali -e -subnet
server-tcp 223.6.6.6 -g china -g ali -e
server 119.29.29.29 -g china -g tencent -e
server-tcp 119.28.28.28 -g china -g tencent -e
server 180.184.1.1 -g china -g bytedance -e
server-tcp 180.184.2.2 -g china -g bytedance -e
server 120.196.165.24 -g china -e
server 1.2.4.8 -g china -e

# ==========================================
# 域名分流规则加载区
# ==========================================
# dnsmasq-china-list
domain-set -name china_list -file /etc_ro/smartdns/accelerated-domains.china.raw.txt
domain-rules /domain-set:china_list/ -nameserver china -speed-check-mode tcp:80
# 阿里
domain-set -name ali_domains -file /etc_ro/smartdns/domains-ali.txt
domain-rules /domain-set:ali_domains/ -nameserver ali
# 腾讯
domain-set -name tencent_domains -file /etc_ro/smartdns/domains-tencent.txt
domain-rules /domain-set:tencent_domains/ -nameserver tencent
# 字节
domain-set -name bytedance_domains -file /etc_ro/smartdns/domains-bytedance.txt
domain-rules /domain-set:bytedance_domains/ -nameserver bytedance
